name: PyPi

on: [create]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello non release ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
