name: PyPi

on: [release]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello x ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
