name: PyPI
on:
  push:
    tags:
      - 0.*
      - 1.*

jobs:
  build:
    if: github.event.base_ref == "refs/head/master"
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2